"""empty message

Revision ID: 64bf20890d93
Revises: ec60220783b5
Create Date: 2020-12-25 14:37:49.463885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bf20890d93'
down_revision = 'ec60220783b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'user', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'user', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    # ### end Alembic commands ###
