"""empty message

Revision ID: ec60220783b5
Revises: 3d5d53ba74bb
Create Date: 2020-12-25 14:36:32.168750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec60220783b5'
down_revision = '3d5d53ba74bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'question', ['followed_id'], ['author_id'])
    op.create_foreign_key(None, 'follow', 'question', ['follower_id'], ['author_id'])
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    # ### end Alembic commands ###
